# -*- coding: utf-8 -*-
"""Maggie_Lab2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YtBzz-xQmXtkh7Q2PMV6fzzxQxp4S79_
"""

FixedMenu1 = "Appetizer"
FixedMenu2 = "Entree"
FixedMenu3 = "Dessert"

MenuTitle1 = "vegetarian MENu"
MenuTitle2 = "noN-VEGetarian menu"

VegeAppetizer = "Olive Plate"
VegeEntree = "Risotto With Steamed Vegetables"
VegeDessert = "Fruit Tart"

VegeAppetizer_Calories = 200
VegeEntree_Calories = 470
VegeDessert_Calories = 265

TotalCal = VegeAppetizer_Calories + VegeEntree_Calories + VegeDessert_Calories
print(TotalCal)

AverageTotCal = TotalCal / 3
print(AverageTotCal)

print(MenuTitle1.upper())
print(FixedMenu1.upper(), "-", VegeAppetizer, "-", VegeAppetizer_Calories)
print(FixedMenu2.upper(), "-" , VegeEntree, "-" , VegeEntree_Calories )
print(FixedMenu3.upper(), "-", VegeDessert, "-", VegeDessert_Calories)

print("-" * 20)
print("Total Calories: ", TotalCal)
print("Average Calories: ", AverageTotCal)

NonVegeAppetizer = "Shrimp Cocktail"
NonVegeEntree = "Chicken Carbonara"
NonVegeDessert = "Rum cake"

NonVegeAppetizer_Calories = 330
NonVegeEntree_Calories = 740
NonVegeDessert_Calories = 585

TotalCalNonVege = NonVegeAppetizer_Calories + NonVegeEntree_Calories + NonVegeDessert_Calories
print(TotalCalNonVege)

AverageTotCalNonVege = int(TotalCalNonVege / 3)
print(AverageTotCalNonVege)

print(MenuTitle1.upper())
print(FixedMenu1.upper(), "-", VegeAppetizer, "-", VegeAppetizer_Calories)
print(FixedMenu2.upper(), "-" , VegeEntree, "-" , VegeEntree_Calories )
print(FixedMenu3.upper(), "-", VegeDessert, "-", VegeDessert_Calories)

print("-" * 20)
print("Total Calories: ", TotalCal)
print("Average Calories: ", AverageTotCal)

print(MenuTitle2.upper())
print(f"{FixedMenu1}: {NonVegeAppetizer} - ({NonVegeAppetizer_Calories} cal)")
print(f"{FixedMenu2}: {NonVegeEntree} - ({NonVegeEntree_Calories} cal)")
print(f"{FixedMenu3}: {NonVegeDessert} - ({NonVegeDessert_Calories} cal)")

print("-" * 20)
print("Total Calories: ", TotalCalNonVege)
print("Average Calories: ", AverageTotCalNonVege)